/-

LICENSE goes here.

-/

import Steinberg.Macro.Group
import Mathlib.Data.Finset.Defs

namespace Steinberg

class PositiveRootSystem (Root : semiOutParam (Type TΦ))
  extends
    ToString Root
  where
  height : Root → Nat

attribute [height_simps] PositiveRootSystem.height

open PositiveRootSystem

abbrev SingleSpanRootPair (Φ : Type TΦ) [PositiveRootSystem Φ] :=
  (ζ : Φ) × (η : Φ) × (θ : Φ) × ℤ ×' (height θ = height ζ + height η)

abbrev DoubleSpanRootPair (Φ : Type TΦ) [PositiveRootSystem Φ] := (
  (ζ : Φ) × (η : Φ) × (θ₁ : Φ) × (θ₂ : Φ)
  × ℤ × ℤ ×' (height θ₁ = height ζ + height η) ×' (height θ₂ = height ζ + 2 * height η)
)

structure PartialChevalleySystem (Φ : Type TΦ) [PositiveRootSystem Φ] where
  mk ::
  -- autogenerated
  present_roots : Set Φ
  trivial_comm_root_pairs : Set (Φ × Φ)
  single_comm_root_pairs : Set (SingleSpanRootPair Φ)
  double_comm_root_pairs : Set (DoubleSpanRootPair Φ)

  h_trivial_valid : ∀ p ∈ trivial_comm_root_pairs, p.1 ∈ present_roots ∧ p.2 ∈ present_roots
  h_single_valid : ∀ p ∈ single_comm_root_pairs, p.1 ∈ present_roots ∧ p.2.1 ∈ present_roots ∧ p.2.2.1 ∈ present_roots
  h_double_valid : ∀ p ∈ double_comm_root_pairs, p.1 ∈ present_roots ∧ p.2.1 ∈ present_roots ∧ p.2.2.1 ∈ present_roots ∧ p.2.2.2.1 ∈ present_roots

namespace PartialChevalleySystem

def mk_full (Φ : Type TΦ) [PositiveRootSystem Φ]
  (present_roots : Set Φ) (trivial_comm_root_pairs : Set (Φ × Φ)) (single_comm_root_pairs : Set (SingleSpanRootPair Φ))
  (double_comm_root_pairs : Set (DoubleSpanRootPair Φ)) (h_full : ∀ (ζ : Φ), ζ ∈ present_roots) : PartialChevalleySystem Φ :=
  PartialChevalleySystem.mk present_roots trivial_comm_root_pairs single_comm_root_pairs double_comm_root_pairs (by tauto) (by tauto) (by tauto)

end PartialChevalleySystem

end Steinberg
